# LAB 2: Linear Regression
# X-y split (y is the target variable, in this case, "total claim amount")

In [5]:
import seaborn as sns
import pandas as pd

In [6]:
df = pd.read_csv(r"C:\Users\Juliane\Documents\GitHub\labs_repo\LessonsW4\marketing_customer_analysis_clean.csv")

In [7]:
df.head(3)

unnamed:_0 customer       state  customer_lifetime_value response coverage  \
0           0  DK49336     Arizona              4809.216960       No    Basic   
1           1  KX64629  California              2228.525238       No    Basic   
2           2  LZ68649  Washington             14947.917300       No    Basic   

  education effective_to_date employmentstatus gender  ...  \
0   College        2011-02-18         Employed      M  ...   
1   College        2011-01-18       Unemployed      F  ...   
2  Bachelor        2011-02-10         Employed      M  ...   

   number_of_policies     policy_type        policy  renew_offer_type  \
0                   9  Corporate Auto  Corporate L3            Offer3   
1                   1   Personal Auto   Personal L3            Offer4   
2                   2   Personal Auto   Personal L3            Offer3   

   sales_channel  total_claim_amount  vehicle_class  vehicle_size  \
0          Agent          292.800000  Four-Door Car       Medsize   
1    Call Center          744.924331  Four-Door Car       Medsize   
2    Call Center          480.000000            SUV       Medsize   

  vehicle_type month  
0            A     2  
1            A     1  
2            A     2  

[3 rows x 27 columns]

In [9]:
dfn = df.select_dtypes(include=['int64', 'float64'])

In [12]:
dfn.columns

Index(['unnamed:_0', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'total_claim_amount', 'month'],
      dtype='object')

In [ ]:
# Train-test split.

In [18]:
X = df[['customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'month']]
y = df[["total_claim_amount"]]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 100)

In [46]:
# Standardize the data (after the data split!)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

c_scale = ['customer_lifetime_value', 'income',
                    'monthly_premium_auto', 'months_since_last_claim',
                    'months_since_policy_inception', 'number_of_open_complaints',
                    'number_of_policies', 'month']

df[c_scale] = scaler.fit_transform(df[c_scale])


In [47]:
c_scale

['customer_lifetime_value',
 'income',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_of_open_complaints',
 'number_of_policies',
 'month']

In [54]:
scaler.fit(X_train)
scaler.transform(X_train)
scaler.transform(X_test)

array([[-0.76043343, -0.35616218, -0.64372705, ..., -0.42923353,
        -0.83292699,  1.06283582],
       [-0.7907347 , -0.5605567 , -0.64372705, ...,  0.70799066,
        -0.83292699,  1.06283582],
       [-0.073986  , -1.23962932,  0.40000755, ..., -0.42923353,
         2.08053707, -0.94087909],
       ...,
       [-0.18143387, -1.23962932,  0.05209602, ..., -0.42923353,
         0.83190962,  1.06283582],
       [-0.59334724,  1.81207528,  0.19705916, ..., -0.42923353,
        -0.83292699,  1.06283582],
       [ 0.05092055,  1.18606345,  0.31302967, ..., -0.42923353,
         2.49674622,  1.06283582]])

In [55]:
X_train

customer_lifetime_value  income  monthly_premium_auto  \
8752              5932.560456   48278                    74   
2531              5295.625697       0                    74   
8626              2397.036098   22283                    65   
9496             27420.813180       0                   112   
3985             14727.505260   97785                    73   
...                       ...     ...                   ...   
350               2476.480866   47918                    62   
79                9312.585034   75986                   115   
8039              4874.665223   67467                    61   
6936             21159.301510       0                   108   
5640              4558.498445       0                    65   

      months_since_last_claim  months_since_policy_inception  \
8752                15.149071                              7   
2531                19.000000                             71   
8626                16.000000                             93   
9496                23.000000                             20   
3985                35.000000                             36   
...                       ...                            ...   
350                  2.000000                             51   
79                  11.000000                             44   
8039                 4.000000                             22   
6936                15.000000                             17   
5640                24.000000                             93   

      number_of_open_complaints  number_of_policies  month  
8752                   0.384256                   4      1  
2531                   0.000000                   3      1  
8626                   0.000000                   1      1  
9496                   0.000000                   2      2  
3985                   0.000000                   2      2  
...                         ...                 ...    ...  
350                    0.000000                   1      2  
79                     0.000000                   3      2  
8039                   0.000000                   9      2  
6936                   0.000000                   2      1  
5640                   0.000000                   9      2  

[8182 rows x 8 columns]

In [66]:
X_test

customer_lifetime_value  income  monthly_premium_auto  \
1250               2810.464447   26790                    71   
5438               2605.599527   20592                    71   
10156              7451.492020       0                   107   
3441              16477.768430   49825                    70   
682                9192.592887   37388                   117   
...                        ...     ...                   ...   
5063              16727.771860   30915                    72   
10053              5067.208338   29095                   127   
3453               6725.043747       0                    95   
9241               3940.123576   92539                   100   
10449              8295.977271   73556                   104   

       months_since_last_claim  months_since_policy_inception  \
1250                       4.0                             41   
5438                      15.0                             81   
10156                      6.0                             63   
3441                      14.0                             27   
682                       30.0                             21   
...                        ...                            ...   
5063                       1.0                              6   
10053                      2.0                             80   
3453                      15.0                              8   
9241                       1.0                             55   
10449                     31.0                              4   

       number_of_open_complaints  number_of_policies  month  
1250                         0.0                   1      2  
5438                         1.0                   1      2  
10156                        0.0                   8      1  
3441                         3.0                   2      2  
682                          0.0                   5      2  
...                          ...                 ...    ...  
5063                         2.0                   2      1  
10053                        0.0                   1      1  
3453                         0.0                   5      2  
9241                         0.0                   1      2  
10449                        0.0                   9      2  

[2728 rows x 8 columns]

# Apply linear regression.

In [57]:
# Creating our model
from sklearn.linear_model import LinearRegression

In [58]:
lm = LinearRegression()

In [59]:
model = lm.fit(X_train, y_train) # where do I put the scale?

In [60]:
model.coef_

array([[-5.94432559e-04, -3.35413017e-03,  5.26490520e+00,
        -1.39022328e-01, -1.77680197e-01, -2.75039018e+00,
         1.77896047e-01, -1.70958415e+00]])

In [61]:
model.intercept_

array([87.81289817])

# Model Interpretation.

In [62]:
import numpy as np

In [ ]:
#'customer_lifetime_value', 'income',
                    # 'monthly_premium_auto', 'months_since_last_claim',
                    'months_since_policy_inception', 'number_of_open_complaints',
                    'number_of_policies', 'month'

In [ ]:
#Predict random

In [70]:
random_tca = np.array([[2810.464447, 26790, 71, 4.0, 41, 0.0, 1, 2]]).reshape(1,-1)

In [71]:
model.predict(random_tca)

C:\Users\Juliane\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[359.01113903]])

# Apply linear regression.

In [72]:
y_pred = np.array(model.predict(X_test))


In [73]:
y_test.reset_index(inplace=True)

In [74]:
pd.DataFrame(y_pred)[0]

0       359.011139
1       368.534973
2       634.413943
3       261.383580
4       562.506569
           ...    
2723    345.189930
2724    639.831179
2725    577.944843
2726    288.420724
2727    376.876725
Name: 0, Length: 2728, dtype: float64

In [75]:
y_pred.shape

(2728, 1)

In [76]:
real_vs_pred = pd.DataFrame({'y_test': y_test["total_claim_amount"], 'y_pred':pd.DataFrame(y_pred)[0]})

In [77]:
real_vs_pred

y_test      y_pred
0     340.800000  359.011139
1     195.153339  368.534973
2     770.400000  634.413943
3     336.000000  261.383580
4     561.600000  562.506569
...          ...         ...
2723  345.600000  345.189930
2724  664.280864  639.831179
2725  684.000000  577.944843
2726   25.713622  288.420724
2727  497.684017  376.876725

[2728 rows x 2 columns]

In [78]:
# Compute the MSE
from sklearn.metrics import mean_squared_error as mse

In [79]:
mse(real_vs_pred['y_test'], real_vs_pred['y_pred'])

42443.37163762149

In [83]:
import math
math.sqrt(42443.37163762149)

206.01789154736412